### ISSUE TITLE
Example dashboards?

### ISSUE THREAD

**Issue by clohtd** [Ulrhol/dashing_opentsdb#1]
Hi,  I was wondering if you had any additional dashboards pulling from OpenTSDB that you could post as examples?

**Comment by Ulrhol** [comment]
Unfortunately not. I made the OpenTSDB dashing stuff just to get more familiar with Ruby. Haven't used it in prodution anywhere so made no additional widgets or examples.

Anything particular you're looking for?

**Comment by clohtd** [comment]
I was just looking for any opportunity to ramp up faster.  If you never used it then I'll do my own digging.  Perhaps I'll end up being able to offer examples of my own.  Thanks for the response.

**Comment by Ulrhol** [comment]
Please feel free. We're stuck with a graphite server but I'd love to go opentsdb at some point and then I'd like some nice widgets to present.
